### ISSUE TITLE
🐛 Development pods with tests that require an app host fail to run tests

### ISSUE THREAD

**Issue by dcacenabes** [swiftyfinch/Rugby#324] opened 2024-02-14 11:27 UTC
## Have you already tried Rugby doctor?
Use `rugby doctor` as a self-diagnostic tool.

## Describe the bug
For development pods, when they require an app host for the test suite to run:
```
  s.test_spec 'Tests' do |test_spec|
   test_spec.source_files = 'Example/Tests/**/*.swift'
   test_spec.requires_app_host = true
   test_spec.app_host_name = 'LocalPod/ExampleApp'
   test_spec.dependency 'LocalPod/ExampleApp'
  end

 s.app_spec 'ExampleApp' do |app_spec|
   app_spec.source_files = 'Example/LocalPod/**/*.swift'
 end
```

Xcode will show an error when trying to run those tests: 
Could not find test host for LocalPod-Unit-Tests: TEST_HOST evaluates to "/Users/cace/Library/Developer/Xcode/DerivedData/RugbyIssueDemo-bwkxyahmiqvauecruatnrxyowmox/Build/Products/Debug-iphonesimulator/LocalPod-ExampleApp.app/LocalPod-ExampleApp"

I checked and it makes sense because in `/Users/cace/Library/Developer/Xcode/DerivedData/RugbyIssueDemo-bwkxyahmiqvauecruatnrxyowmox/Build/Products/Debug-iphonesimulator/` there is no LocalPod-ExampleApp.app folder, there is only `LocalPod-Unit-Tests.xctest/` and `LocalPod_Unit_Tests.swiftmodule/`

## To Reproduce
I produce a sample project that demonstrates the issue:
[RugbyIssueDemo.zip](https://github.com/swiftyfinch/Rugby/files/14278755/RugbyIssueDemo.zip)

1. Go to Tests section, and run the LocalPod-Unit-Tests
![Screenshot 2024-02-14 at 12 20 11](https://github.com/swiftyfinch/Rugby/assets/3796899/265ff591-6890-4e05-95cb-47d62dd0ee6f)
2. See an error `Could not find test host for LocalPod-Unit-Tests: TEST_HOST evaluates to "/Users/cace/Library/Developer/Xcode/DerivedData/RugbyIssueDemo-bwkxyahmiqvauecruatnrxyowmox/Build/Products/Debug-iphonesimulator/LocalPod-ExampleApp.app/LocalPod-ExampleApp" `

In case you don't want to use the example project, this can be reproduced by creating a podspec for a development pod that contains:
```
s.source_files = 'LocalPod/Classes/**/*'

  s.test_spec 'Tests' do |test_spec|
   test_spec.source_files = 'Example/Tests/**/*.swift'
   test_spec.requires_app_host = true
   test_spec.app_host_name = 'LocalPod/ExampleApp'
   test_spec.dependency 'LocalPod/ExampleApp'
  end

 s.app_spec 'ExampleApp' do |app_spec|
   app_spec.source_files = 'Example/LocalPod/**/*.swift'
 end
```

And then in the Podfile:
```
pod 'LocalPod', :path => 'Modules/LocalPod', :testspecs => ['Tests']
```

## Expected behavior
Tests should run

## Screenshots
![Screenshot 2024-02-14 at 12 21 37](https://github.com/swiftyfinch/Rugby/assets/3796899/1aee23af-f62e-4a92-bf44-336b9f6527e8)

## Environment (please complete the following information):
 - Version 2.4.5
 - Logs (use `rugby doctor`)

```rugby doctor
🚑 If you have any problems, please try these solutions.
After each one, you need to repeat your usual workflow.
(⌘ + double click on the url) to open it in a browser.

1. Update 🏈 Rugby to the latest version: rugby update
   github.com/swiftyfinch/Rugby/blob/2.4.5/Docs/commands-help/update.md
2. Check that you're building the proper configuration.
   Sometimes projects don't have the default Debug config.
   rugby cache --config Your-Not-Debug-Config
   github.com/swiftyfinch/Rugby/blob/2.4.5/Docs/commands-help/shortcuts/cache.md
4. Add ignore option: rugby cache --ignore-cache.
   Be careful, you can't pass this option to plan command this way.
   github.com/swiftyfinch/Rugby/blob/2.4.5/Docs/commands-help/shortcuts/cache.md
5. Try rugby clear before repeating your usual workflow.
   github.com/swiftyfinch/Rugby/blob/2.4.5/Docs/commands-help/clear.md
6. Try to clean up your DerivedData and use rugby clear together.
7. Check that the Pods project builds successfully without 🏈 Rugby.

By the way, you can try to investigate building logs by yourself.
Last ones saved in folder: ~/.rugby/logs/14.02.2024T11.18.21

Open an issue/discussion on GitHub or by any convenient support channel.
Attach the last logs, but be sure that there are no sensitive data.
github.com/swiftyfinch/Rugby/issues
github.com/swiftyfinch/Rugby/discussions```
 - Podfile or Example project (if you can share these)
   [RugbyIssueDemo.zip](https://github.com/swiftyfinch/Rugby/files/14278755/RugbyIssueDemo.zip)

## Additional context
The key thing here is that the test target requires an app host. If we remove the necessity of an app host, tests work as expected.

**Comment by swiftyfinch** [comment] 2024-02-14 18:20
@dcacenabes Hello! Yeah, you are right, it's a bug for sure.
Thank you for detailed description 👍

The problem is Rugby 🏈 shouldn't cache products with an application type.
I will fix it soon. Right now you can use `--except LocalPod-ExampleApp` option as a temporary fix.

**Comment by swiftyfinch** [comment] 2024-02-15 16:45
@dcacenabes It should be fixed here: 🏈 [v2.5.0](https://github.com/swiftyfinch/Rugby/releases/tag/2.5.0)

**Comment by swiftyfinch** [comment] 2024-02-17 08:43
Feel free to reopen it if the issue is still present in the latest version

**Closed by swiftyfinch** 2024-02-17 08:43 UTC
Labels: bug

**Comment by dcacenabes** [comment] 2024-02-22 11:19
Ouch, sorry I never replied. Thanks a bunch for the fix!!!
