### ISSUE TITLE
Rugby cache fails for Appboy - missing xcfilelist

### ISSUE THREAD

**Issue by r2-pro** [swiftyfinch/Rugby#198] opened 2022-10-05 09:53 UTC
## Describe the bug
Rugby cache failing on

![Screenshot 2022-10-05 at 11 46 14](https://user-images.githubusercontent.com/105044156/194032109-6e007160-620a-4c99-bac6-006f37ac5cc4.png)

I have been looking for the mentioned filename in the whole project but I do not see where it is defined.
It does not help also when I exclude Appboy from being cached.

I would welcome any hints that could tell me more what is happening.

## To Reproduce
1. Just run `rugby cache -arch arm64`
2.  Error occures.

## Expected behavior
Framework is built.

## Environment (please complete the following information):
 - Version 1.20.0
 - Logs (use `rugby doctor`)
 - Podfile or Example project (if you can share these)

## Additional context

[build.log](https://github.com/swiftyfinch/Rugby/files/9714621/build.log)
[rawBuild.log](https://github.com/swiftyfinch/Rugby/files/9714622/rawBuild.log)
[rugby.log](https://github.com/swiftyfinch/Rugby/files/9714623/rugby.log)

**Comment by swiftyfinch** [comment] 2022-10-05 18:33
@r2-pro Hello! I checked your log files, but I don't know the certain scenario to reproduce such issue.

Could you clone Rugby and try to reproduce this issue in `Rugby/TestProject`? You can add some of your pods to `TestProject/Podfile`.
If you can break this project and share the commit with me it will help me a lot.

As alternative, you can share your pods from Podfile and I can try to break and fix it by myself. But I'm not sure that I will find right scenario for reproducing the issue.

**Comment by r2-pro** [comment] 2022-10-10 09:08
I have tried just using `rugby` with TestProject from rugby repo and the error is similar even without additional depdendency.

[build.log](https://github.com/swiftyfinch/Rugby/files/9744564/build.log)
[rawBuild.log](https://github.com/swiftyfinch/Rugby/files/9744565/rawBuild.log)
[rugby.log](https://github.com/swiftyfinch/Rugby/files/9744566/rugby.log)

It helps when I remove from Podfile:
```
installer.pods_project.root_object.build_configuration_list.build_configurations.each { |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  }
```

[build.log](https://github.com/swiftyfinch/Rugby/files/9744579/build.log)
[rawBuild.log](https://github.com/swiftyfinch/Rugby/files/9744580/rawBuild.log)
[rugby.log](https://github.com/swiftyfinch/Rugby/files/9744582/rugby.log)

We do have similar settings in our Podfile, but it does not help with the issue.

[build.log](https://github.com/swiftyfinch/Rugby/files/9744609/build.log)
[rawBuild.log](https://github.com/swiftyfinch/Rugby/files/9744610/rawBuild.log)
[rugby.log](https://github.com/swiftyfinch/Rugby/files/9744611/rugby.log)

**Comment by swiftyfinch** [comment] 2022-10-10 16:29
@r2-pro Thank you for more information! Yeah, I see.

But why do you need to exclude `arm64` for `simulator` and after that try to compile `arm64` for simulator with 🏈 Rugby?
It should not work in this way. If you try to build with Xcode you get `x86_64 simulator`, because you exclude `arm64` by yourself.

> It helps when I remove from Podfile:
> ```
> installer.pods_project.root_object.build_configuration_list.build_configurations.each { |config|
>     config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
> }
> ```
> `rugby cache --arch arm64`

So, I think you need to follow these points:
1. If you want to build `arm64 simulator` you need to remove this `EXCLUDED_ARCHS` setting;
2. If you want to build `arm64 device` you need to call `rugby cache -a arm64 -s ios` or even `rugby cache -s ios`;
3. If you want to build `x86_64 simulator` you need to use `rugby cache`.

Maybe I didn't catch you problem?

**Comment by r2-pro** [comment] 2022-10-11 07:33
I guess it is the first point, `arm64 simulator` or rather, whatever I need to prepare cache that can be used to run on a simulator on a M1 machine. Yet no matter what I do, the error is the same.

Also, have you thought to build `xcframeworks` instead with all architectures in place?

**Comment by swiftyfinch** [comment] 2022-10-11 16:17
OK, but did you remove your `EXCLUDED_ARCHS` for simulator from your `Podfile` and run `pod install` after that?
```diff
installer_representation.pods_project.build_configurations.each do |config|
-   config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    config.build_settings['EXCLUDED_ARCHS[sdk=iphoneos*]'] = 'armv7'
end
```
If you want to use arm64 for m1 simulator you need to do it.

Another option is use `x86_64` for `m1 simulator`. But it good only if you have problems with building your modules for `arm64 simulator`.

Also, I will try to reproduce this situation on CI. But I'm pretty sure, that you just need to remove `EXCLUDED_ARCHS` as I mentioned above.


There was a topic about XCFramework: https://github.com/swiftyfinch/Rugby/discussions/35.
For now, I decided not to use XCFrameworks. But you can build several archs and sdks like so:
```shell
rugby cache --arch x86_64 arm64 arm64 --sdk sim sim ios
```

**Comment by swiftyfinch** [comment] 2022-10-24 09:11
@r2-pro Hello! Do you have any updates here?

**Comment by swiftyfinch** [comment] 2022-11-08 16:45
@r2-pro Sorry, I will close this issue soon.
Please, add more comments to make this discussion alive.

**Comment by swiftyfinch** [comment] 2022-11-09 16:26
@r2-pro Sorry, could you use the last Rugby 🏈 version and build TestProject again?
Also, please remove `DerivedData` folder and call `rugby clean` in TestProject folder.

I checked these logs and can't reproduce this even without removing `excluded_archs` from `post_install` hook in Podfile.
https://github.com/swiftyfinch/Rugby/issues/198#issuecomment-1273009473

This is my Podfile:
```ruby
platform :ios, '11.0.2'
project 'TestProject/TestProject.xcodeproj'

install! 'cocoapods', :warn_for_unused_master_specs_repo => false

target 'TestProject' do
    use_frameworks!

    # Appboy-iOS-SDK
    pod 'Segment-Appboy'

    target 'TestProjectTests' do
        inherit! :search_paths
    end
    
    target 'TestProjectUITests' do
        # None
    end
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.name == 'Debug'
                config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-Onone']
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
            end
            if config.name != 'Release'
                config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
            end
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
            config.build_settings['OTHER_LDFLAGS'] = '$(inherited) "-ObjC"' if target.name == 'Appboy-iOS-SDK'
        end
    end
    
    installer_representation.pods_project.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphoneos*]'] = 'armv7'
    end
end
```

And I got such log:
```shell
* Rugby version: 1.20.3
* Command: rugby cache --arch arm64
* Xcode 14.0 / Build version 14A309
* Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
* CPU: Apple M1
* Project: Pods
* Git branch: main
---------------------------------
Prepare Read project ✓
Prepare Backup Pods/Pods.xcodeproj
Prepare Backup Pods/Target Support Files
Prepare Pods (4):
Prepare * Analytics
Prepare * Appboy-iOS-SDK
Prepare * SDWebImage
Prepare * Segment-Appboy
Prepare Calculate checksums ✓
Prepare Additional build targets (4):
Prepare * Appboy-iOS-SDK-Appboy
Prepare * Appboy-iOS-SDK-AppboyUI.ContentCards
Prepare * Appboy-iOS-SDK-AppboyUI.InAppMessage
Prepare * Appboy-iOS-SDK-AppboyUI.NewsFeed
Prepare Resolving dependencies graph
Prepare Build targets (8):
Prepare * Analytics
Prepare * Appboy-iOS-SDK
Prepare * Appboy-iOS-SDK-Appboy
Prepare * Appboy-iOS-SDK-AppboyUI.ContentCards
Prepare * Appboy-iOS-SDK-AppboyUI.InAppMessage
Prepare * Appboy-iOS-SDK-AppboyUI.NewsFeed
Prepare * SDWebImage
Prepare * Segment-Appboy
Prepare Add build target: RugbyPods
Prepare Save project ✓
[1s] Prepare ✓
Build Building sim-arm64: Debug ✓
Build Update checksums ✓
[6s] Build ✓
Integration Update paths to built pods ✓
[1s] Integration ✓
Clean up Read project ✓
Clean up Remove sources from project
Clean up Remove frameworks
Clean up Remove products
Clean up Remove build target
Clean up Remove built pods
Clean up Remove schemes
Clean up Save project ✓
[1s] Clean up ✓
[8s] Cached 4/4 pods.
[!] Project size ↓82%
[!] Indexing files count ↓98%
[!] Targets count ↓72%
[8s] Let's roll 🏈
```

**Comment by swiftyfinch** [comment] 2022-12-25 13:50
Hello @r2-pro! Are there any news?
You can try to use [🏈 Remastered (Early Beta)](https://github.com/swiftyfinch/Rugby/releases/tag/2.0.0b2).

I'm going to close this issue. Feel free to reopen it with more information.

**Closed by swiftyfinch** 2022-12-25 13:50 UTC
Labels: bug, awaiting response

**Comment by bluepi0j** [comment] 2023-02-15 15:50
@swiftyfinch I got the similar issue when I run `rugby cache -a arm64` in TestProject In Intel laptop, there is no error in console, but there is no binary file created

```warning: None of the architectures in ARCHS (arm64) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (arm64, arm64e, i386, x86_64) which is not in EXCLUDED_ARCHS (arm64). (in target 'Keyboard+LayoutGuide' from project 'Pods')```

<img width="860" alt="image" src="https://user-images.githubusercontent.com/3591809/219077550-6833bec3-88be-47b4-a1b1-73747c1bb4d5.png">


[build.log](https://github.com/swiftyfinch/Rugby/files/10744820/build.log)
[rawBuild.log](https://github.com/swiftyfinch/Rugby/files/10744823/rawBuild.log)
[rugby.log](https://github.com/swiftyfinch/Rugby/files/10744824/rugby.log)

**Comment by swiftyfinch** [comment] 2023-02-15 18:33
@bluepi0j Hello! Did you try to comment this line in Podfile?
https://github.com/swiftyfinch/Rugby/blob/main/TestProject/Podfile#L44

If you want to build for arm64 you don't need to exclude it.
Also, maybe there is something similar in the root TestProject.

**Comment by bluepi0j** [comment] 2023-02-16 02:13
@swiftyfinch thank you, it works for me

**Comment by swiftyfinch** [comment] 2023-02-16 04:51
@bluepi0j You're welcome!
