### ISSUE TITLE
🐛 Cannot build rugby

### ISSUE THREAD

**Issue by manav1mg** [swiftyfinch/Rugby#182] opened 2022-08-04 11:03 UTC
## Did you already try Rugby doctor?
Use `rugby doctor` as a self-diagnostic tool.

## Describe the bug
While building using rugby, i am facing issue.

## To Reproduce
1. Deleted derived folder
2. pod install && rugby

## Expected behavior
It should build pods.

## Screenshots
<img width="564" alt="Screenshot 2022-08-04 at 4 28 49 PM" src="https://user-images.githubusercontent.com/91203002/182831526-0c368751-2d4a-455b-b591-1effb7e331b4.png">

## Environment (please complete the following information):
 - Version [1.19.1]
 - Logs ('GoogleUtilities/UserDefaults/Public/GoogleUtilities/GULUserDefaults.h' file not found)

**Comment by swiftyfinch** [comment] 2022-08-04 14:54
Hello @manav1mg! I added `pod 'GoogleUtilities'` in Podfile of TestProject in this repository and rugby managed successfully build it.

<img width="426" alt="Screenshot 2022-08-04 at 19 51 11" src="https://user-images.githubusercontent.com/64660122/182877773-d9c174bb-c375-44bf-b553-f4a57b0c9ff8.png">

I can't reproduce this issue. Please, add additional information or try to break TestProject in this repository and share your git diff in this conversation.

**Comment by swiftyfinch** [comment] 2022-08-22 16:00
@manav1mg Hey! Do you have any updates here?
Can we close this issue?

**Comment by swiftyfinch** [comment] 2022-08-31 03:23
@manav1mg Hey! I'm closing this issue due to inactivity.
Feel free to add more info and reopen it.

**Closed by swiftyfinch** 2022-08-31 03:23 UTC
Labels: bug, need more info, awaiting response
