### ISSUE TITLE
🐛 Space Characters in Project Path Not Handled

### ISSUE THREAD

**Issue by VaslD** [swiftyfinch/Rugby#221] opened 2023-03-10 06:43 UTC
## Did you already try Rugby doctor?

`rugby doctor` is unavailable in 2.0.0 :-(

## Describe the bug

When the Xcode project is located in a directory whose path includes space (and potentially other special characters), Rugby succeeds in building frameworks but fails to somehow move them.

## To Reproduce

1. Create a project named "Example 2", or just rename an existing project folder to some other name with spaces.
2. `pod init` and add some Pod, e.g. `Alamofire`. (Then `pod install`.)
3. `rugby build` or `rugby build -t Alamofire`.
4. Rugby runs for some time and exits with missing files error. Files actually exist in `./.rugby/build`.

## Expected behavior

Rugby should ideally handle all kinds of file paths allowed by the filesystem.

## Screenshots

![Screenshot 03-10 14 32 15@2x](https://user-images.githubusercontent.com/3415065/224241904-db9728e7-e360-4014-bb96-0d53aa502a58.png)

## Environment (please complete the following information):

Xcode 14.1 & 14.2
Rugby 2.0.0b6
macOS Ventura 13.2.1

## Additional context

I just found out that Rugby created an additional "Example\ 2" (the backslash is copied here as-is, not an escape sequence; never knew this file name was allowed by APFS!) folder alongside the original "Example 2" project folder. This might be the reason why it couldn't find built frameworks.

**Comment by swiftyfinch** [comment] 2023-03-10 15:43
Hello @World! Thanks a lot for detailed description 👍🏻

I reproduced an issue with escaping paths for shell commands.
I will test this fix on weekend. If everything is OK, I will release the next version around Monday.

Right now you can avoid spaces in your project path.

**Comment by swiftyfinch** [comment] 2023-03-12 10:35
@VaslD It fixed in [the RC2](https://github.com/swiftyfinch/Rugby/releases/tag/2.0.0b7).

**Comment by cog-iagentur** [comment] 2023-10-26 08:36
Did the fix made it to latest release 2.12.2 @swiftyfinch? I am having the same issue when project path has a space.

**Comment by swiftyfinch** [comment] 2023-10-26 17:13
@cog-iagentur Hello! Yeah, I managed to reproduce the issue with a project path.
It looks like easy fix, but I need to add some tests. I will do it soon.

**Closed** 2023-10-26 18:28 UTC
Labels: bug
