### ISSUE TITLE
🐛 Rugby not working if we use Flutter inside project.

### ISSUE THREAD

**Issue by shreesha-kedilaya** [swiftyfinch/Rugby#148] opened 2022-05-13 17:25 UTC
## Describe the bug
- If i use rugby without flutter integration it will not have other pod dependencies showing in pods target.
- But if use with flutter it will add all the pods that flutter needs to the pods target and it is failing. Below attached ss.
<img width="995" alt="Screenshot 2022-05-13 at 10 45 25 PM" src="https://user-images.githubusercontent.com/75058896/168334772-f67c438c-a2d7-452b-97af-1a695aaa632d.png">

## To Reproduce
- Create a flutter project.
- Integrate the flutter using this link https://docs.flutter.dev/development/add-to-app/ios/project-setup and use Option A.
- Then do pod install through rugby you will succeed and it will create Frameworks folder inside our codebase.
- But because the flutter is doing some random thing its adding other pod dependencies inside pod target and then its failing.

## Screenshots

<img width="676" alt="Screenshot 2022-05-13 at 10 39 03 PM" src="https://user-images.githubusercontent.com/75058896/168335200-1d52d453-378b-4aa6-b4eb-75e68133e923.png">

## Environment (please complete the following information):
 - Xcode 13.2.1
 
Rugby clean report.

```
    Clean Removed .rugby/build
    Clean Removed .rugby/cache.yml
    [1s] Clean ✓
```

- Example podfile
```
    use_frameworks!
    
    platform :ios, '11.0'
    
    def shared_ui_pod
      pod 'RxSwift'
      pod 'RxCocoa'
      pod 'AlamofireImage'
      pod 'lottie-ios'
    end
    
     submodule linkage
    flutter_application_path = './Flutter/'
    load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
    
    target 'Project' do
    
      # this is only needed for targets using flutter
      install_all_flutter_pods(flutter_application_path)
    
      use_frameworks!
      shared_ui_pod
      app_dependencies
```

**Comment by swiftyfinch** [comment] 2022-05-14 12:19
Hello! Could you break TestProject from this repository and open merge request?
It will help me to investigate this issue. I'm not sure when I can look into Flutter installation guide and I don't have Flutter on my macbook.

**Comment by shreesha-kedilaya** [comment] 2022-05-16 13:50
@swiftyfinch Created a PR https://github.com/swiftyfinch/Rugby/pull/149. Please check this. And also please run `make setup_flutter` to install all flutter dependencies before running `pod install && rugby`

**Comment by swiftyfinch** [comment] 2022-05-16 19:06
Thank you @shreesha-kedilaya! I will check it.

**Comment by swiftyfinch** [comment] 2022-05-17 17:08
Sorry, I have some problems with brew:
```
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  software update --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.3.
```

Probably, I will return to this only on weekend. Let me know if y have some solutions.
I already tried different Xcode versions, checked CLT, reinstall brew.

**Comment by shreesha-kedilaya** [comment] 2022-05-17 17:16
Which brew version are you using? @swiftyfinch

**Comment by shreesha-kedilaya** [comment] 2022-05-17 19:09
@swiftyfinch Created another PR [https://github.com/swiftyfinch/Rugby/pull/150](url).

You can install flutter from [this](https://docs.flutter.dev/get-started/install?gclid=CjwKCAjwj42UBhAAEiwACIhADr45YEmcx4HZe-eH9S0b3LEYnxIyM4N-jywfJkqbkrd-a4UF3scrKBoCw60QAvD_BwE&gclsrc=aw.ds) link. Download zip and unzip. Update your path variables. Then you are setup.

Then you can run `make setup_flutter` or `make sync_flutter` (if already ran `make setup_flutter` once).

**Comment by swiftyfinch** [comment] 2022-05-18 08:10
@shreesha-kedilaya Thanks a lot! You've done so much!
Finally, I've managed to reproduce this issue.
I will try to come back with a solution.

**Comment by swiftyfinch** [comment] 2022-05-19 18:07
@shreesha-kedilaya You can use `rugby -e FirebaseCrashlytics`.
I didn't find better solution.

Also, I have another one issue:
```
~/Library/Developer/Xcode/DerivedData/FlutterRugbyIntegration-dmvcmyvucltpyuhhtsmxtkwutntt/Build/Intermediates.noindex/FlutterRugbyIntegration.build/Debug-iphonesimulator/FlutterRugbyIntegration.build/Script-11757BDF2832328400E2F34C.sh: line 6: ~/Downloads/Rugby-main/Flutter_test_app/Flutter/.ios/Flutter/flutter_export_environment.sh: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by shreesha-kedilaya** [comment] 2022-05-20 14:41
@swiftyfinch This solution works for me. That issue is maybe because you are not using fvm for flutter.

Will be waiting for better solution. But huge thanks for this workaround.

**Comment by swiftyfinch** [comment] 2022-05-21 10:48
As I understand the problem is in Flutter Firebase integration.

In public headers of binary we don't have such header:
<img width="632" alt="Screenshot 2022-05-21 at 15 29 38" src="https://user-images.githubusercontent.com/64660122/169648092-242c255e-8b40-4aca-aa7f-fbbd93cd9e8c.png">

<img width="288" alt="Screenshot 2022-05-21 at 15 29 56" src="https://user-images.githubusercontent.com/64660122/169648114-f7409c3d-62b5-4cef-8ac7-2074a28db04a.png">

But it exists in Pods folder:
<img width="298" alt="Screenshot 2022-05-21 at 15 31 06" src="https://user-images.githubusercontent.com/64660122/169648133-15da36bc-cb82-4d64-9417-60f993e638ca.png">

Probably, I don't have enough knowledge, but it looks like you can't use binary here with such Flutter Firebase integration.

**Comment by shreesha-kedilaya** [comment] 2022-05-23 14:36
Any reason why we are not actually flutter side dependencies. I think the problem is residing here. Im assuming your build/cache pipeline is failing here?

**Comment by swiftyfinch** [comment] 2022-05-24 03:39
What I have already checked:
* Rugby works as expected here ✅ 
* CocoaPods also works perfectly including Firebase pods ✅ 
* As I see the problem only in Flutter Firebase integration part 🚫

Probably, you can find some issues like this: https://github.com/firebase/flutterfire/issues/8756 and it will help you.
Or maybe you can ask there how to use it as binary and why it doesn't work in such way.

Or you can just skip Firebase from Rugby process with `--exclude FirebaseCrashlytics ` flag as I mentioned above.

Sorry, I can't suggest better solution from Rugby side.
Let me know if you find additional information or I will close the issue during 2 days.
Best regards

**Comment by shreesha-kedilaya** [comment] 2022-05-24 05:19
@swiftyfinch We will use `--exclude FirebaseCrashlytics`. But found discrepancy in pod targets with flutter and without flutter integration

Without flutter it only has target `Pods-FlutterRugbyIntegration`
<img width="536" alt="Screenshot 2022-05-24 at 10 45 01 AM" src="https://user-images.githubusercontent.com/16717916/169954308-16aed55b-8bf4-48a5-a6fd-96c2da95482e.png">

With flutter it has all flutter related targets. So wondering because flutter `firebase_crashlytics` is not cached its referring parent pod `FirebaseCrashlytics` which is cached in rugby. Maybe because of this its failing. Ref screen shot below. 
<img width="382" alt="Screenshot 2022-05-24 at 10 45 25 AM" src="https://user-images.githubusercontent.com/16717916/169954655-27bd83f6-41f2-453e-a90c-700a701b79de.png">

**Comment by swiftyfinch** [comment] 2022-05-24 06:45
@shreesha-kedilaya Yeah, it's fine. Rugby caches only pods targets except root ones like `Pods-*`. And it knows nothing about Flutter targets.

**Comment by shreesha-kedilaya** [comment] 2022-05-24 16:28
@swiftyfinch please look at this PR https://github.com/swiftyfinch/Rugby/pull/152. I found something strange. We had both local and remote pods. But you were only cacheing remote pods. So i merged both and then ran the command. It is working in our project. Please check this. Please refer below ss for reference 
<img width="468" alt="Screenshot 2022-05-24 at 9 56 31 PM" src="https://user-images.githubusercontent.com/16717916/170085950-b2b9eb21-4049-4ffe-81d2-3494bb040e6b.png">

**Comment by swiftyfinch** [comment] 2022-05-24 18:51
@shreesha-kedilaya Oh, yeah) that works for me too.
But you do not need to make such changes. Just use `rugby --focus ""`.
https://github.com/swiftyfinch/Rugby/blob/main/Docs/Cache.md#build-local-pods

I'm not sure if caching local pods is correct solution for you case.
But that's already something)

**Comment by shreesha-kedilaya** [comment] 2022-05-25 07:34
Thanks so much @swiftyfinch for this. This also works. Will integrate this in our project. This helps a lot. It reduced 30 - 40 % of our build time.

**Comment by swiftyfinch** [comment] 2022-05-25 08:20
@shreesha-kedilaya You're welcome! Glad to hear it!

**Comment by swiftyfinch** [comment] 2022-05-27 06:24
@shreesha-kedilaya Feel free to reopen this issue if the problem is still exists.
Also, I will close your pull requests #149 #150 #152

**Closed by swiftyfinch** 2022-05-27 06:24 UTC
Labels: bug, awaiting response
