### ISSUE TITLE
Can't cache pods with steps like "Copy XCFrameworks"

### ISSUE THREAD

**Issue by PRESIDENT810** [swiftyfinch/Rugby#250] opened 2023-10-11 18:47 UTC
Hi!

I was trying to build a Xcode projects using some pods like "realm", and I found out that if a pod has steps such as "Copy XCFrameworks" or "Copy generated compatibility header", rugby won't do these steps. When building the APP, it gives me errors like this:

<img width="1401" alt="image" src="https://github.com/swiftyfinch/Rugby/assets/44538064/5bd537a3-f9ab-46dd-bd91-c3833a0cf4b4">

<img width="1393" alt="image" src="https://github.com/swiftyfinch/Rugby/assets/44538064/f4fad629-0d53-4692-ad1f-d6f2df10dd6f">

I'm new to iOS development so I don't know what exactly happened. My guess is rugby somehow ignored these steps, so when building with rugby, Xcode can't find those copied files.

After I rollback rugby and build normally, it finds the correct xcframework files and successfully builds the project
<img width="959" alt="image" src="https://github.com/swiftyfinch/Rugby/assets/44538064/a113e79b-c21a-4170-a0db-f41d4dfb54d3">

## To Reproduce
Just create an empty Xcode project using this pod: realm

## Environment (please complete the following information):
 - Version 2.1.0

**Comment by swiftyfinch** [comment] 2023-10-12 19:39
@PRESIDENT810 Thank you for detailed description 👍
I don't have a solution right now. I'll try to investigate.

**Comment by PRESIDENT810** [comment] 2023-10-17 23:09
@swiftyfinch  
I'm thinking if it's possible to identify those targets, and tell rugby not to cache them? Although we still can't cache these pods, at least it's a workaround so it can skip non-cacheable targets automatically.
I'm no Xcode expert but I think the reason why we can't cache "Copy XCFrameworks" or "Copy generated compatibility header" is because it's executing a shell script, and its input & output are not clear. Is it possible to determine if a target has build phases that executing a shell script? And if so, maybe we can let rugby make these targets as if they show up in --except?

**Comment by swiftyfinch** [comment] 2023-10-18 18:28
@PRESIDENT810 Yeah, I think you are right 👍
We can do it, but I was going to investigate this problem deeper.

There was similar exclusion logic in `Rugby1.x`:
https://github.com/swiftyfinch/Rugby/blob/1.23.0/Sources/Rugby/Common/XcodeProj/Target/XcodeProj%2BExcludeXCFrameworksTargets.swift#L15

Also, there is low coverage percent. So, we need to write more tests on this part.
And then we can add this check or maybe we can manage this case in different way.

Thank you for your description of the problem 👍

**Comment by PRESIDENT810** [comment] 2023-10-27 00:56
I think I knew how to fix it @swiftyfinch 
So when these pods copy xcframeworks, they are executing a shell script, and the core part is this:
```
install_xcframework() {
  local basepath="$1"
  local name="$2"
  local package_type="$3"
  local paths=("${@:4}")

  # Locate the correct slice of the .xcframework for the current architectures
  select_slice "${basepath}" "${paths[@]}"
  local target_path="$SELECT_SLICE_RETVAL"
  if [[ -z "$target_path" ]]; then
    echo "warning: [CP] $(basename ${basepath}): Unable to find matching slice in '${paths[@]}' for the current build architectures ($ARCHS) and platform (${EFFECTIVE_PLATFORM_NAME-${PLATFORM_NAME}})."
    return
  fi
  local source="$basepath/$target_path"

  local destination="${PODS_XCFRAMEWORKS_BUILD_DIR}/${name}"

  if [ ! -d "$destination" ]; then
    mkdir -p "$destination"
  fi

  copy_dir "$source/" "$destination"
  echo "Copied $source to $destination"
}
```
As you can see, the destination is determined by `PODS_XCFRAMEWORKS_BUILD_DIR`, which is a env var determined by Cocoapod. I don't know the underlying process very clearly, but I would guess Cocoapod determines this directory using something like this: `$(BUILD_DIR)/$(CONFIGURATION)$(PLATFORM)/XCFrameworkIntermediates`.

So if we are not using rugby, this path is `$HOME/Library/Developer/Xcode/DerivedData/TeslaV4-eqdwrmayxcjgbdaivanjwvvezssv/Build/Products/Internal-iphoneos/XCFrameworkIntermediates/`, where `$HOME/Library/Developer/.../Products` is `$(BUILD_DIR)`, and `Internal-iphoneos` is `$(CONFIGURATION)$(PLATFORM)`.

However, when we are using rugby, somehow `$(BUILD_DIR)` becomes `$PROJECT_DIR/.rugby/build`, that makes `PODS_XCFRAMEWORKS_BUILD_DIR` become `$PROJECT_DIR/.rugby/build/Internal-iphoneos/XCFrameworkIntermediates`, and that's where rugby put these libraries. I didn't read the source code throughly but I guess you are replacing BUILD_DIR to be the local cache directory or doing something similar in rugby.

So when rugby builds these targets, these scripts are executed and libraries are generated. It's just not in DerivedData directory but in the local rugby cache directory.

Nevertheless, when we build the main target in Xcode, since this has nothing to do with rugby, `BUILD_DIR` becomes `HOME/Library/Developer/Xcode/DerivedData/TeslaV4-eqdwrmayxcjgbdaivanjwvvezssv/Build/Products` again, but this is not where rugby put these libraries, so Xcode can't find them for sure.

I guess the fix is fairly simple, just add some search path in Xcode project to make sure it searches things under `$PROJECT_DIR/.rugby/build/Internal-iphoneos/XCFrameworkIntermediates` as well, then it should be fixed.

<img width="1318" alt="image" src="https://github.com/swiftyfinch/Rugby/assets/44538064/1216a6da-a16d-41a5-b332-e10b3ca00c70">
I manually added these and Xcode successfully found these libraries. I think rugby can automatically detect any path that contains `BUILD_DIR` and replace it with local cache directory's path, then add these path to library search path. I don't there are side effects by adding more search path, so that should be a quick way to fix it I guess.

**Comment by swiftyfinch** [comment] 2023-10-27 19:40
@PRESIDENT810 Thank you for your thoughts 👍

Unfortunately, There is a one disadvantage. Rugby will move all files from `project_dir/.rugby/build/config_dir` to `~/.rugby/bin`. And then they should be ready to upload to any cloud. So, I think we can't find `XCFrameworkIntermediates` folder if we don't send it to cloud too. Also, Rugby will remove target after this, so there will not be a place to run `[CP] Copy XCFrameworks` script for sure.

But I thought about your idea. I think we can patch script and all paths before building with Rugby.

<img width="830" alt="Screenshot 2023-10-27 at 23 57 39" src="https://github.com/swiftyfinch/Rugby/assets/64660122/d3d0a95f-861b-4d60-9ff8-c26d29b76d6e"><br>


So, it will look like this:

<img width="259" alt="Screenshot 2023-10-28 at 00 26 11" src="https://github.com/swiftyfinch/Rugby/assets/64660122/747bb5fc-33c9-4fac-9525-4184eadde553">

It works in this scenario, but I need some time to add the additional step for libraries with `[CP] Copy XCFrameworks` script. You can try to reproduce this.

```diff
# Example/Pods/Target Support Files/Realm-library/Realm-library-xcframeworks.sh
- local destination="${PODS_XCFRAMEWORKS_BUILD_DIR}/${name}"
+ local destination="${PODS_CONFIGURATION_BUILD_DIR}/${PRODUCT_NAME}/${name}"
```

```diff
# Example/Pods/Target Support Files/Pods-ExampleLibs/Pods-ExampleLibs.debug.xcconfig
- "${PODS_XCFRAMEWORKS_BUILD_DIR}/Realm"
+ "${HOME}/.rugby/bin/Realm-library/${CONFIGURATION}${EFFECTIVE_PLATFORM_NAME}-${ARCHS}/df20354/Realm"
-  "${PODS_XCFRAMEWORKS_BUILD_DIR}/Realm/Headers"
+ "${HOME}/.rugby/bin/Realm-library/${CONFIGURATION}${EFFECTIVE_PLATFORM_NAME}-${ARCHS}/df20354/Realm/Headers"
```

----

There is another disadvantage. If there are several targets with the same scripts, they will copy their xcframeworks. So, them will not be shared. I think that it's strange situation, and such targets should have xcframeworks wrapped into dependencies instead of scripts.

**Comment by PRESIDENT810** [comment] 2023-10-27 22:38
@swiftyfinch If I'm understanding it correctly, you want to put XCFrameworks under `~/.rugby/bin` so it will stay in cache and be reused across different project or hosts, and make library search path points to that path, right? I guess that would work.

I just wonder why we can't just copy `project_dir/.rugby/build/Internal-iphoneos/XCFrameworkIntermediates` to `~/.rugby/build/Internal-iphoneos/XCFrameworkIntermediates` along with other libraries, and add new search paths for everything under `~/.rugby/build/Internal-iphoneos/XCFrameworkIntermediates`, so we don't need to patch scripts?

Also I'm not really sure what this means (probably because I really don't know much about Xcode):
> If there are several targets with the same scripts, they will copy their xcframeworks. So, they will not be shared.
I would really appreciate some explanation if you got time, thanks!

**Comment by PRESIDENT810** [comment] 2023-10-27 23:56
Btw I think I know what's going on with "Copy generated compatibility header". It's something similar.

```
PODS_CONFIGURATION_BUILD_DIR = ${PODS_BUILD_DIR}/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_XCFRAMEWORKS_BUILD_DIR = $(PODS_CONFIGURATION_BUILD_DIR)/XCFrameworkIntermediates
```
Seems this is how Cocoapod determine these paths. Due to `PODS_BUILD_DIR` is changed during rugby caching, these artifacts will be put in either project's `.rugby` directory or `~/.rugby` directory, depending on if they are moved.

So in my project, this causes a few problems:
- Swift compatibility header are missing. 
For example, one is in `~/.rugby/bin/ExpoModulesCore/Internal-iphoneos-arm64/2b8d7c6/Swift Compatibility Header`. I guess this is moved from project's `.rugby` directory. And since the original header search path is `${PODS_CONFIGURATION_BUILD_DIR}/ExpoModulesCore/Swift Compatibility Header`, it's pointing to `~/Library/Developer/Xcode/DerivedData/TeslaV4-eqdwrmayxcjgbdaivanjwvvezssv/Build/Products/Internal-iphoneos/ExpoModulesCore/Swift Compatibility Header` when you are building in Xcode.
- Frameworks are not found
For example, the framework is in `~/github/mobile-app/ios/.rugby/build/Internal-iphoneos/XCFrameworkIntermediates/payment-react-native/AlipaySDK.framework` due to the same reason as XCFramework case. The original framework search path is `${PODS_XCFRAMEWORKS_BUILD_DIR}/GooglePlaces` which points to `/Users/kainzhong/Library/Developer/Xcode/DerivedData/TeslaV4-eqdwrmayxcjgbdaivanjwvvezssv/Build/Products/Internal-iphoneos/XCFrameworkIntermediates`. Again, I need to add paths under `$PROJECT_DIR/.rugby/build/Internal-iphoneos/XCFrameworkIntermediates` to make Xcode find these frameworks.

So I guess the root cause is the different `PODS_CONFIGURATION_BUILD_DIR` path between when caching using rugby and when building using Xcode. I guess we can fix this by 1. copying all necessary stuff under `PROJECT_DIR/.rugby` to the global rugby cache and 2. Find all search paths with PODS_XCFRAMEWORKS_BUILD_DIR and PODS_XCFRAMEWORKS_BUILD_DIR, then replace or add new search paths pointing to the global rugby cache directory.

Hope this helps

**Comment by swiftyfinch** [comment] 2023-10-28 13:59
> @swiftyfinch If I'm understanding it correctly, you want to put XCFrameworks under `~/.rugby/bin` so it will stay in cache and be reused across different project or hosts, and make library search path points to that path, right? I guess that would work.
> 
> I just wonder why we can't just copy `project_dir/.rugby/build/Internal-iphoneos/XCFrameworkIntermediates` to `~/.rugby/build/Internal-iphoneos/XCFrameworkIntermediates` along with other libraries, and add new search paths by replacing every search path with prefix `PODS_XCFRAMEWORKS_BUILD_DIR` to `~/.rugby/build/Internal-iphoneos/XCFrameworkIntermediates` (or just replace `PODS_XCFRAMEWORKS_BUILD_DIR` to that), so we don't need to patch scripts?

I think we can do it too. But we need a strategy to clean `~/.rugby/build` from time to time or it can contain infinity of unused legacy products. And if we clean this folder, it can cause to problems, because the copy scripts had already removed.
And we still need to add additional step to move `XCFrameworkIntermediates` to `~/.rugby/build`.

It looks a bit unmanaged to me. But this solution have an advantage, we don't need to upload `XCFrameworkIntermediates` to a cloud.

> Also I'm not really sure what this means (probably because I really don't know much about Xcode):
> 
> > If there are several targets with the same scripts, they will copy their xcframeworks. So, they will not be shared.
> 
> I would really appreciate some explanation if you got time, thanks!

Never mind :) I've meant that there can be several targets which produce the same `XCFrameworkIntermediates`. So if we move these `XCFrameworkIntermediates` to their products, probably we will duplicate them in size. But I think it pretty unbelievable case.

**Comment by swiftyfinch** [comment] 2023-10-29 07:58
@PRESIDENT810 Hello! Could you test a draft #261?
It works on my projects 🆗.

**Comment by PRESIDENT810** [comment] 2023-10-30 20:35
@swiftyfinch That works for my project, too. Thanks for the fix!

**Comment by PRESIDENT810** [comment] 2023-11-01 00:27
@swiftyfinch I'm so sorry but when I said that patch worked, I actually meant it only worked for "[CP] Copy XCFrameworks" but not for "Copy generated compatibility header"... 
I guess for "Copy generated compatibility header", we also should replace the Swift Compatibility Header path like this:
```
private let SWIFT_COMPATIBILITY_HEADERS = "Swift Compatibility Header"

            if product.type == .staticLibrary {
                result.append((
                    "\(PODS_XCFRAMEWORKS_BUILD_DIR)\(moduleName)/\(HEADERS)",
                    replacement: "\(binaryFolderPath)/\(moduleName)/\(HEADERS)"
                ))
                result.append((
                    "\(PODS_XCFRAMEWORKS_BUILD_DIR)\(moduleName)",
                    replacement: "\(binaryFolderPath)/\(moduleName)"
                ))
>                result.append((
>                    "\(PODS_CONFIGURATION_BUILD_DIR)\(moduleName)/\(SWIFT_COMPATIBILITY_HEADERS)",
>                    replacement: "\(binaryFolderPath)/\(SWIFT_COMPATIBILITY_HEADERS)"
                ))
            }

```
in `SupportFilesPatcher`'s `prepareXCConfigReplacements` method. Seems this works for our project.

**Comment by swiftyfinch** [comment] 2023-11-01 09:43
@PRESIDENT810 Oops, let's reopen it 😅

Do you want to add this fix? And we need to change tests a little bit.

**Comment by swiftyfinch** [comment] 2023-11-01 09:44
@PRESIDENT810 And, could you suggest a pod to reproduce this issue?

**Comment by PRESIDENT810** [comment] 2023-11-01 19:34
@swiftyfinch I'm using React Native, and the pod that trigger this problem is this:
https://github.com/expo/expo/blob/48a111d8d005375047bd3c33267fee2e9d6697e6/packages/expo-modules-core/ExpoModulesCore.podspec#L56
I also tried to reproduce this using other pods, like Alamofire, but seems that doesn't automatically add this user_header_search_paths to allow you import swift stuff in ObjC code. I manually add this to Header Search Paths, but the substitution I proposed seems to be not replacing this path after `rugby cache`

<img width="959" alt="image" src="https://github.com/swiftyfinch/Rugby/assets/44538064/d00f62ac-581a-4d7c-95b3-11edc78799a0">

That's weird... Am I doing this in a wrong way? I think in my project, this path is in User-Defined -> PODS_HEADER_SEARCH_PATHS instead of Searth Paths -> Header Search Paths. Probably I should add the compatibility header here? I don't have much experience with iOS development so this is quite confusing to me.

**Comment by swiftyfinch** [comment] 2023-11-02 17:49
@PRESIDENT810 No problem, I can try to fix it.

But unfortunately, I couldn't add this module.
I've tried:
```sh
yarn add expo-modules-core
bundle exec pod install --project-directory=ios --repo-update
xed ios
```
But I can't see the new module `ExpoModulesCore` after run these commands.

Also, I've tried to use your project [`RugbyTest`](https://github.com/PRESIDENT810/RugbyTest), but it looks like you use there internal links.
```
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://artifactory.teslamotors.com/artifactory/api/npm/digital-products-node/react/-/react-18.3.0-next-fecc288b7-20221025.tgz: getaddrinfo ENOTFOUND artifactory.teslamotors.com".
```

**Comment by swiftyfinch** [comment] 2023-11-02 18:08
@PRESIDENT810 Also, I've tried to reproduce this issue with `ReactiveCocoa` pod.
There is `Copy generated compatibility header` too, but everything is fine.

**Comment by PRESIDENT810** [comment] 2023-11-02 18:37
> @PRESIDENT810 No problem, I can try to fix it.
> 
> But unfortunately, I couldn't add this module. I've tried:
> 
> ```shell
> yarn add expo-modules-core
> bundle exec pod install --project-directory=ios --repo-update
> xed ios
> ```
> 
> But I can't see the new module `ExpoModulesCore` after run these commands.
> 
> Also, I've tried to use your project [`RugbyTest`](https://github.com/PRESIDENT810/RugbyTest), but it looks like you use there internal links.
> 
> ```
> info There appears to be trouble with your network connection. Retrying...
> error An unexpected error occurred: "https://artifactory.teslamotors.com/artifactory/api/npm/digital-products-node/react/-/react-18.3.0-next-fecc288b7-20221025.tgz: getaddrinfo ENOTFOUND artifactory.teslamotors.com".
> ```

@swiftyfinch I'm so sorry I forgot I'm using our yarn registry. I updated my repo and removed yarn.lock. This time I think it will  work.
I was following https://reactnative.dev/docs/environment-setup so I used these
```
yarn create expo-app AwesomeProject

cd AwesomeProject
yarn expo start
```

As for compatibility header, I think after introduce this pod, you need to include ReactiveCocoa-Swift.h in your ObjC code. Our main project is ObjC so in order to use Swift code in ObjC, we need to include the compatibility header.

**Comment by PRESIDENT810** [comment] 2023-11-03 20:24
@swiftyfinch Ah geez, our project is using #import "Something" all the time so no wonder I keep seeing compatibility header not found error. I changed that to @import Something and it fixed all header not found errors, pure magic!
Sorry I didn't know this before... I really don't have much experience in iOS dev. I guess now everything is fixed

**Comment by swiftyfinch** [comment] 2023-11-04 06:03
@PRESIDENT810 Wow! It's great news!
No problem) I have a plan to update the docs and I should add this information there.

Thank you for your feedback! I'm closing the issue.

**Closed by swiftyfinch** 2023-11-04 06:03 UTC
Labels: bug, hacktoberfest, help welcome
